//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public int r_Id { get; set; }
        public int p_Id { get; set; }
        public bool DeliveryStatus { get; set; }
        public System.DateTime DeliveryTime { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Rider Rider { get; set; }
    }
}
