//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabAppDbEntities : DbContext
    {
        public LabAppDbEntities()
            : base("name=LabAppDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Rider> Riders { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
